import Head from "next/head";
import FamousPlaces from "../components/FamousPlaces";
import Searchbox from "../components/Searchbox";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='home'>
        <div className="container">
          <Searchbox placeholder={"Search for a city"} />
          <FamousPlaces/>
        </div>
      </div>
    </div>
  );
}
